function build_tiresuspension(outdir, overrides, useVDB)
%   useVDB = true puts VDB's Independent Suspension - Double Wishbone into the
%   model to produce the wheel kinematics, driven by our own suspension
%   deflection. Step 2 of docs/vdb_plant_migration.md. Default false, so the
%   shipped plant is untouched until the variant has been A/B'd against it.
%BUILD_TIRESUSPENSION  Fill in IFSSIM_TireSuspension.
%
%   Every force that steers, accelerates or stops the car is generated here.
%
%   The TYRE ITSELF is Simscape Vehicle Dynamics Blockset's Combined Slip
%   Wheel 2DOF block -- a full Magic Formula 6.2 tyre -- vectorised across all
%   four corners in a single instance. What this file still owns is everything
%   AROUND it: the suspension that decides the vertical load, the kinematics
%   that turn a body-frame state into per-wheel contact-patch velocities, the
%   drive/brake/rolling torques that go onto the axle, and the assembly of
%   four wheel forces back into a body wrench.
%
%   Magic Formula is a better-STRUCTURED tyre, not better tyre data. Its
%   coefficients are generated by build_tyre_paramset from the same B/C/E fit
%   we already had. What it buys is real combined slip instead of a friction
%   ellipse, and a curve whose own tail sets sliding grip -- so the guessed
%   peak-to-slide ratio the Fiala version needed is gone.
%
%   The block's own brake and vertical models are switched off (BrakeType and
%   vertType = None) because we already model both. There is no rolling
%   resistance switch on this block -- Magic Formula always computes it -- so
%   its QSY coefficients are zeroed in the parameter set instead, leaving the
%   plant's own settled Crr to act as an axle torque.
%
%   Vertical load therefore goes IN through Fext and comes back out unchanged
%   as Fz -- verified, not assumed. Wheel spin is a state INSIDE the block now;
%   it used to be integrated here.
%
%   Simplified still: quasi-static suspension (no unsprung-mass DOF), no
%   thermal model, camber held at zero.

if nargin < 1 || isempty(outdir)
    outdir = fullfile(fileparts(mfilename('fullpath')), 'models');
end
addpath(fileparts(mfilename('fullpath'))); addpath(outdir);
if nargin < 2, overrides = struct(); end
if nargin < 3, useVDB = false; end
P = ifssim_load_workspace(overrides);

name = 'IFSSIM_TireSuspension';
if bdIsLoaded(name), close_system(name,0); end
f = fullfile(outdir,[name '.slx']);
if isfile(f), delete(f); end

new_system(name,'Model');
% ode1, NOT FixedStepDiscrete. The Fiala block carries continuous states and a
% discrete solver refuses to compile a model containing them. ode1 is forward
% Euler at the same fixed step, so every block that was already discrete steps
% exactly as it did before -- this widens what the model can contain, it does
% not change how the existing content is integrated.
%
% The step must be BIT-IDENTICAL to the parent plant's; see the long note on
% STEP in build_plant_skeleton.m for why it is 2 ulp off 1/960.
set_param(name,'SolverType','Fixed-step','Solver','ode1', ...
               'FixedStep','0.0010416666666666671','StartTime','0','StopTime','inf');

%% ---- inputs -----------------------------------------------------------
add_block('simulink/Sources/In1',[name '/Road'],'Position',[30 40 60 60], ...
          'OutDataTypeStr','Bus: IFSSIM_RoadBus','BusOutputAsStruct','on');
add_block('simulink/Signal Routing/Bus Selector',[name '/Road Select'], ...
          'Position',[130 20 140 120],'OutputSignals','valid,height,mu,residual');
add_line(name,'Road/1','Road Select/1','autorouting','on');

add_block('simulink/Sources/In1',[name '/Pose'],'Position',[30 160 60 180], ...
          'OutDataTypeStr','Bus: IFSSIM_PoseBus','BusOutputAsStruct','on');
add_block('simulink/Signal Routing/Bus Selector',[name '/Pose Select'], ...
          'Position',[130 140 140 240],'OutputSignals','position,quat,vel_body,omega_body');
add_line(name,'Pose/1','Pose Select/1','autorouting','on');

vecIn = {'steer','drive_torque','brake_torque'};
y = 280;
for i = 1:numel(vecIn)
    add_block('simulink/Sources/In1',[name '/' vecIn{i}],'Position',[30 y 60 y+20], ...
              'PortDimensions','4');
    y = y + 60;
end

%% ---- suspension and kinematics ---------------------------------------
PRE = 'Suspension and Kinematics';
pre = [name '/' PRE];
add_block('simulink/User-Defined Functions/MATLAB Function', pre, ...
          'Position',[250 40 430 420]);
S = sfroot;
cpre = S.find('-isa','Stateflow.EMChart','Path',pre);
cpre.Script = pre_code();
set_sizes(cpre, struct( ...
  'road_valid',4,'road_h',4,'road_mu',4,'road_res',4, ...
  'pos',3,'quat',4,'velb',3,'omegab',3, ...
  'steer_in',4,'drive_t',4,'brake_t',4,'w_fb',4, ...
  'Fz',4,'Vxw',4,'Vyw',4,'AxlTrq',4,'steer_o',4, ...
  'susp_travel',4,'in_contact',4,'muScale',[27 4],'camber',4, ...
  'WhlPz',4,'WhlVz',4));
add_params(cpre, {'IFSSIM_arbF','IFSSIM_arbR', ...
                  'IFSSIM_Ts','IFSSIM_Iw','IFSSIM_wreg','IFSSIM_aF','IFSSIM_bR','IFSSIM_tF','IFSSIM_tR','IFSSIM_Rw', ...
                  'IFSSIM_kwF','IFSSIM_kwR','IFSSIM_cw','IFSSIM_L0','IFSSIM_FzF','IFSSIM_FzR', ...
                  'IFSSIM_camF','IFSSIM_camR','IFSSIM_cgainF','IFSSIM_cgainR', ...
                  'IFSSIM_mu','IFSSIM_Crr'});

%% ---- the tyre ---------------------------------------------------------
% One instance, four corners. Every port carries a 4-vector; the block is
% built to vectorise and this was confirmed by compiling it at width 4 before
% anything here depended on it.
TY = 'Tyre';
ty = [name '/' TY];
load_system('vehdynlibtire');
add_block('vehdynlibtire/Combined Slip Wheel 2DOF', ty, 'Position',[520 120 640 300]);

% CONFIGURING THIS BLOCK IS ORDER-DEPENDENT, and the order below is the only
% one that works headlessly. It was established by experiment, because the
% implementation behind the mask is P-coded and the behaviour is documented
% nowhere:
%
%  1. tireType = 'External file' FIRST. While tireType names a built-in tyre,
%     the coefficients come from that preset's dataset and every value written
%     into the dialog is ignored. Switching to 'External file' is what makes
%     the dialog fields authoritative.
%
%  2. THE COEFFICIENTS ARE WRITTEN ONE BY ONE, not loaded from the file. The
%     'Tire file or object' field only populates the dialog, and it does so
%     from a mask callback that opens a FILE DIALOG -- calling it under
%     matlab -batch fails with "Creating dialog boxes ... is not supported".
%     So the generated .mat is the source of truth and this loop transcribes
%     it into the block. Writing only SOME of them produces a tyre that
%     generates no force at all, because the set is then internally
%     inconsistent; it is all of them or none.
%
%  3. The configuration popups go LAST. Every dialog write re-runs the mask
%     initialisation, which puts vertType back to 'Magic Formula' -- and that
%     computes Fz from ground penetration rather than taking it from Fext, so
%     the tyre silently reports zero vertical load and the car has no grip.
TP   = build_tyre_paramset(outdir, overrides);
% One recipe, shared with tyre_report so the report cannot validate a
% configuration the plant does not actually use. Every ordering constraint in
% there was established by experiment; see the comments in the function.
nset = configure_tyre_block(ty, TP);

% Ports the block still exposes but this car does not drive. Camber is zero
% because the suspension model has no camber DOF; YawRate feeds turn-slip,
% which needs a steer RATE we do not currently produce; Gnd is inert with the
% vertical model off; pressure is set equal to nominal so its ratio is 1.
% Camber is no longer a constant: the suspension computes it. YawRate feeds
% turn-slip, which needs a steer RATE we do not produce; Gnd is inert with
% the vertical model off; pressure equals nominal so its ratio is 1.
konst = {'YawRate','0'; 'Prs','IFSSIM_Ppres'; 'Gnd','0'};
yk = 340;
for i = 1:size(konst,1)
    add_block('simulink/Sources/Constant',[name '/' konst{i,1}], ...
              'Position',[400 yk 460 yk+20], ...
              'Value',['ones(4,1)*' konst{i,2}]);
    yk = yk + 40;
end

%% ---- wheel forces back to the body ------------------------------------
POST = 'Wheel Forces';
post = [name '/' POST];
add_block('simulink/User-Defined Functions/MATLAB Function', post, ...
          'Position',[720 60 880 380]);

S = sfroot;
cpost = S.find('-isa','Stateflow.EMChart','Path',post);
cpost.Script = post_code();
set_sizes(cpost, struct( ...
  'Fx_in',4,'Fy_in',4,'Fz_in',4,'Om',4,'steer_in',4,'Vxw',4,'Vyw',4, ...
  'omega',4,'fz',4,'fx',4,'fy',4,'slip_ratio',4,'slip_angle',4, ...
  'tyre_force',3,'tyre_torque',3));
add_params(cpost, {'IFSSIM_aF','IFSSIM_bR','IFSSIM_tF','IFSSIM_tR', ...
                   'IFSSIM_Rw','IFSSIM_vreg','IFSSIM_CoGH'});

%% ---- wheel-speed feedback ---------------------------------------------
% The block integrates wheel spin itself, but our brake and rolling-resistance
% torques both need to know which way the wheel is turning before they can
% oppose it. Taking Omega straight back into the axle torque would be an
% algebraic loop, so it goes through a one-step delay.
add_block('simulink/Discrete/Memory',[name '/wheel omega (delay)'], ...
          'Position',[520 420 590 450],'InitialCondition','0');
% MEMORY, not Unit Delay. Both break the loop, but a Unit Delay declares a
% DISCRETE RATE, and that made this model a hybrid of discrete and continuous
% components -- at which point Simulink stops being lenient and demands that
% the parent and referenced model agree on step size to the last bit of the
% double. They never did: both sides are negotiated fundamental sample times,
% the plant landing on 0.0010416666666666671 and this model on ...667, and no
% literal written on either side changes that, because neither is parsed.
% Memory carries no rate of its own, so the model stays continuous and the
% question of matching never arises.

%% ---- outputs ----------------------------------------------------------
add_block('simulink/Signal Routing/Bus Creator',[name '/Wheels Bus'], ...
          'Position',[940 40 950 320],'Inputs','9', ...
          'OutDataTypeStr','Bus: IFSSIM_WheelsBus','NonVirtualBus','on');
add_block('simulink/Sinks/Out1',[name '/Wheels'],'Position',[1000 170 1030 190], ...
          'OutDataTypeStr','Bus: IFSSIM_WheelsBus');
add_line(name,'Wheels Bus/1','Wheels/1','autorouting','on');
add_block('simulink/Sinks/Out1',[name '/tyre_force'],'Position',[1000 360 1030 380], ...
          'PortDimensions','3');
add_block('simulink/Sinks/Out1',[name '/tyre_torque'],'Position',[1000 420 1030 440], ...
          'PortDimensions','3');
% Info is a 27-field diagnostic bus. Nothing downstream consumes it.
add_block('simulink/Sinks/Terminator',[name '/Info'],'Position',[720 20 740 40]);
% Mx/My/Mz: overturning, rolling-resistance and self-aligning moments. The
% chassis takes a force and a moment arm from us, not per-wheel moments, so
% these are deliberately dropped -- but they must still be TERMINATED, or the
% model has unconnected ports and will not compile.
for mo = {'Mx','My','Mz'}
    add_block('simulink/Sinks/Terminator',[name '/' mo{1}], ...
              'Position',[720 400 740 420]);
end

%% ---- wiring -----------------------------------------------------------
% Indices are written as running offsets, never as literals. The last time
% they were literals a bus gained a field and the mis-wiring type-checked
% perfectly, because every port on this boundary is a double.
nRoad = 4;   % valid, height, mu, residual
nPose = 4;   % position, quat, vel_body, omega_body
for i = 1:nRoad, add_line(name,sprintf('Road Select/%d',i),sprintf('%s/%d',PRE,i),'autorouting','on'); end
for i = 1:nPose, add_line(name,sprintf('Pose Select/%d',i),sprintf('%s/%d',PRE,nRoad+i),'autorouting','on'); end
for i = 1:3,     add_line(name,[vecIn{i} '/1'],sprintf('%s/%d',PRE,nRoad+nPose+i),'autorouting','on'); end
add_line(name,'wheel omega (delay)/1',sprintf('%s/%d',PRE,nRoad+nPose+4),'autorouting','on');

% pre -> tyre.  Port order on the block under THIS configuration is
% AxlTrq, Vx, Vy, Camber, YawRate, Prs, Gnd, Fext, ScaleFctr -- read off the
% block itself, because switching the brake model off deletes a port and
% renumbers everything after it.
pOut = struct('Fz',1,'Vxw',2,'Vyw',3,'AxlTrq',4,'steer_o',5, ...
              'susp_travel',6,'in_contact',7,'muScale',8,'camber',9, ...
              'WhlPz',10,'WhlVz',11);
% NOTE THE ORDER: this block puts Fext at 7 and Gnd at 8, which is the
% OPPOSITE of the Fiala block that used to sit here. Read off the block, not
% carried over -- swapping those two silently feeds ground height in as
% vertical load and the car has no grip at all.
add_line(name,sprintf('%s/%d',PRE,pOut.AxlTrq), [TY '/1'],'autorouting','on');
add_line(name,sprintf('%s/%d',PRE,pOut.Vxw),    [TY '/2'],'autorouting','on');
add_line(name,sprintf('%s/%d',PRE,pOut.Vyw),    [TY '/3'],'autorouting','on');
if ~useVDB
    add_line(name,sprintf('%s/%d',PRE,pOut.camber), [TY '/4'],'autorouting','on');
    tag_camber_probe(name, TY);

    % WhlPz and WhlVz exist for the VDB suspension block and nothing else, so
    % in this configuration they are computed and go nowhere. They still have
    % to be TERMINATED rather than left dangling: verify_plant_skeleton checks
    % connectivity separately from compilation, precisely because a model with
    % loose ports compiles perfectly well and is still wrong. Leaving them
    % unconnected is what made the plant check fail, and the check was right.
    for z = {'WhlPz','WhlVz'}
        yy = 640 + 30*(strcmp(z{1},'WhlVz'));
        add_block('simulink/Sinks/Terminator',[name '/unused_' z{1}], ...
                  'Position',[470 yy 490 yy+16]);
        add_line(name,sprintf('%s/%d',PRE,pOut.(z{1})),['unused_' z{1} '/1'], ...
                 'autorouting','on');
    end
else
    % ---- VDB Independent Suspension - Double Wishbone --------------------
    % Step 2 of docs/vdb_plant_migration.md. It produces the wheel KINEMATICS
    % -- camber here, and caster, toe and roll-centre migration once they are
    % wired -- driven by the deflection our own suspension pass already
    % computes. Its force output is NOT taken -- it is terminated below. The
    % load path stays where the tests point until step 3 moves it, and moving
    % it needs a max(Fz,0) clamp the block does not do.
    %
    % Steering is not fed either (StrgAng held at zero), so the steer-coupled
    % slopes are all set to zero to match. Wiring real steer angle in is what
    % turns on bump steer and caster change; it is not part of step 2.
    %
    % NO ALGEBRAIC LOOP, and that was measured rather than assumed: WhlFx and
    % WhlFy do not reach WhlF or WhlAng at all. A 1000 N lateral force showed
    % up only in VehF's y row and moved nothing else, so the tyre's forces do
    % not have to come back round and no delay is needed.
    load_system('vehdynlibsuspension');
    DW = [name '/Suspension Kinematics'];
    add_block('vehdynlibsuspension/Independent Suspension - Double Wishbone', ...
              DW, 'Position',[300 470 430 610]);
    [camF, hslpF] = vdb_camber_mask(P.Susp.StaticCamberFront, P.Susp.CamberGainFront, ...
                        P.TrackFront, P.Derived.StaticLoadFront, P.Derived.WheelRateFront);
    [camR, hslpR] = vdb_camber_mask(P.Susp.StaticCamberRear,  P.Susp.CamberGainRear, ...
                        P.TrackRear,  P.Derived.StaticLoadRear,  P.Derived.WheelRateRear);
    set_param(DW, ...
        'NumAxl','2','NumWhlsByAxl','[2 2]','StrgEnByAxl','[1 0]', ...
        'IdealSuspEn','off', ...      % ON zeroes every kinematics output
        'Kz',  sprintf('[%.10g %.10g]', P.Derived.WheelRateFront, P.Derived.WheelRateRear), ...
        'Cz',  sprintf('%.10g', P.Derived.SuspensionDampingCoeff), ...
        'F0z', sprintf('[%.10g %.10g]', P.Derived.StaticLoadFront, P.Derived.StaticLoadRear), ...
        'Camber',     sprintf('[%.10g %.10g]', camF, camR), ...
        'CamberHslp', sprintf('[%.10g %.10g]', hslpF, hslpR), ...
        'Toe','0','RollStrgSlp','0','ToeStrgSlp','0', ...
        'Caster','0','CasterHslp','0','CasterStrgSlp','0','CamberStrgSlp','0', ...
        ... % ---- the anti-roll bar ------------------------------------------
        ... % Taking the block's WhlF without this would silently delete our roll
        ... % stiffness and rebalance the car. The block models the bar as a
        ... % torsion spring on a sweeping arm, not as a roll rate, so the
        ... % conversion needs the arm length. Measured:
        ... %     dFz_1 = -(K/R^2) * (WhlPz_1 - WhlPz_2) * k(dz/R)
        ... % against our  Karb*(delta_1 - delta_2)/t^2,  so K = Karb*R^2/t^2.
        ... %
        ... % k is the arm sweeping and is NOT a fitting error: 0.98 at the 31 mm
        ... % of travel 3 deg of roll gives on a 0.2 m arm, falling to 0.66 by
        ... % dz/R = 0.8. The bar softens as it works where ours was dead linear.
        ... % That is a real behaviour change and vdb_step3_check reports its size.
        ... %
        ... % NtrlAng MUST be zeroed -- it defaults to 0.5236 rad, which preloads
        ... % the bar with 30 deg of twist it should not have.
        'AntiSwayEnByAxl','[1 1]', ...
        'AntiSwayNtrlAng','[0 0]', ...
        'AntiSwayR',    sprintf('[%.10g %.10g]', P.Susp.ArbArmRadiusFront, P.Susp.ArbArmRadiusRear), ...
        'AntiSwayTrsK', sprintf('[%.10g %.10g]', ...
            P.Derived.ArbFront * P.Susp.ArbArmRadiusFront^2 / P.TrackFront^2, ...
            P.Derived.ArbRear  * P.Susp.ArbArmRadiusRear^2  / P.TrackRear^2), ...
        ... % Hmax is the block's travel limit. It defaults to 0.5 m, two
        ... % hundred millimetres beyond anything this car does, so the block
        ... % supplies NO bump stop at our settings. Neither did the closed form.
        ... % Modelling one is a separate job, not a side effect of this step.
        'Hmax','0.5');

    % The inputs it does not get from us. VehP MUST be zero: fed our corner
    % positions it turned -590.8/-758.1 N into +5464/+5297.
    zc = {'dw_Re', sprintf('%.10g*ones(1,4)', P.WheelRadius), [150 470 210 490]
          'dw_Fx', 'zeros(1,4)', [150 500 210 520]
          'dw_Fy', 'zeros(1,4)', [150 530 210 550]
          'dw_M',  'zeros(3,4)', [150 560 210 580]
          'dw_VehP','zeros(3,4)',[150 590 210 610]
          'dw_VehV','zeros(3,4)',[150 620 210 640]
          'dw_Strg','zeros(1,2)',[150 650 210 670]};
    for z = 1:size(zc,1)
        add_block('simulink/Sources/Constant',[name '/' zc{z,1}], ...
                  'Value',zc{z,2},'Position',zc{z,3});
    end
    % add_line wants names relative to the system, not full paths.
    DWN = 'Suspension Kinematics';
    add_line(name,sprintf('%s/%d',PRE,pOut.WhlPz), [DWN '/1'],'autorouting','on');
    add_line(name,'dw_Re/1',                        [DWN '/2'],'autorouting','on');
    add_line(name,sprintf('%s/%d',PRE,pOut.WhlVz), [DWN '/3'],'autorouting','on');
    add_line(name,'dw_Fx/1',  [DWN '/4'],'autorouting','on');
    add_line(name,'dw_Fy/1',  [DWN '/5'],'autorouting','on');
    add_line(name,'dw_M/1',   [DWN '/6'],'autorouting','on');
    add_line(name,'dw_VehP/1',[DWN '/7'],'autorouting','on');
    add_line(name,'dw_VehV/1',[DWN '/8'],'autorouting','on');
    add_line(name,'dw_Strg/1',[DWN '/9'],'autorouting','on');

    % WhlAng is [3 x 4]; row 1 is camber, in radians, mirrored left to right.
    add_block('simulink/Signal Routing/Selector',[name '/dw_camber'], ...
              'NumberOfDimensions','2','IndexOptions','Index vector (dialog),Index vector (dialog)', ...
              'Indices','1,[1 2 3 4]','InputPortWidth','[3 4]','Position',[470 540 510 570]);
    add_block('simulink/Math Operations/Reshape',[name '/dw_cam4'], ...
              'OutputDimensionality','Customize','OutputDimensions','[4 1]', ...
              'Position',[540 540 570 570]);
    add_line(name,[DWN '/6'],'dw_camber/1','autorouting','on');
    add_line(name,'dw_camber/1','dw_cam4/1','autorouting','on');
    add_line(name,'dw_cam4/1',  [TY '/4'],'autorouting','on');
    tag_camber_probe(name, TY);

    % ---- step 3: the block's WhlF becomes the tyre's vertical load --------
    % WhlF is [3 x 4] on output 4; row 3 is vertical, positive up.
    %
    % Two things the block does not do and must be done here:
    %
    %   CLAMP. It returns -3446 N at 0.20 m of droop -- a tyre pulling the car
    %   down onto the road. A suspension model with no ground contact in it
    %   cannot know the wheel has left the road, so this is a wiring
    %   requirement, not a defect in the block.
    %
    %   CONTACT. Whether there is ground under the wheel at all is ours: it
    %   needs road validity and the platform's plane-fit residual, neither of
    %   which the block can see. in_contact already carries that, and it also
    %   folds in our own Fz > 0 test -- so at the margin the gate is decided by
    %   our force and the magnitude by the block's. They can only disagree
    %   where both are within the ARB nonlinearity of zero, and the clamp
    %   covers that.
    add_block('simulink/Signal Routing/Selector',[name '/dw_fz_row'], ...
              'NumberOfDimensions','2','IndexOptions','Index vector (dialog),Index vector (dialog)', ...
              'Indices','3,[1 2 3 4]','InputPortWidth','[3 4]','Position',[470 380 510 410]);
    add_block('simulink/Math Operations/Reshape',[name '/dw_fz4'], ...
              'OutputDimensionality','Customize','OutputDimensions','[4 1]', ...
              'Position',[540 380 570 410]);
    add_block('simulink/Discontinuities/Saturation',[name '/dw_fz_clamp'], ...
              'UpperLimit','inf','LowerLimit','0','Position',[600 380 630 410]);
    add_block('simulink/Math Operations/Product',[name '/dw_fz_gate'], ...
              'Inputs','2','Multiplication','Element-wise(.*)','Position',[660 380 690 410]);
    add_line(name,[DWN '/4'],'dw_fz_row/1','autorouting','on');
    add_line(name,'dw_fz_row/1','dw_fz4/1','autorouting','on');
    add_line(name,'dw_fz4/1','dw_fz_clamp/1','autorouting','on');
    add_line(name,'dw_fz_clamp/1','dw_fz_gate/1','autorouting','on');
    add_line(name,sprintf('%s/%d',PRE,pOut.in_contact),'dw_fz_gate/2','autorouting','on');
    add_line(name,'dw_fz_gate/1',[TY '/7'],'autorouting','on');    % Fext
    tag_probe(name,'dw_fz_gate',1,'fz_block');

    % Our own Fz is KEPT and logged, not deleted. It is what vdb_step3_check
    % compares the block against, in the same run rather than across two
    % builds, and it is what in_contact is still decided on.
    add_block('simulink/Sinks/Terminator',[name '/dw_fz_ref'],'Position',[470 330 490 346]);
    add_line(name,sprintf('%s/%d',PRE,pOut.Fz),'dw_fz_ref/1','autorouting','on');
    tag_probe(name,PRE,pOut.Fz,'fz_ours');

    % Info, VehF, VehM and WhlV stay terminated. VehF/VehM are the block's own
    % wrench on the body; taking those is a chassis decision, coupled to step
    % 4, and feeding tyre Fx/Fy into WhlFx/WhlFy buys NOTHING until then --
    % measured: they reach VehF only, never WhlF or WhlAng.
    for z = [1 2 3 5]
        add_block('simulink/Sinks/Terminator',[name '/dwT' num2str(z)], ...
                  'Position',[470 460+22*z 490 476+22*z]);
        add_line(name,sprintf('%s/%d',DWN,z),['dwT' num2str(z) '/1'],'autorouting','on');
    end
end
add_line(name,'YawRate/1',                      [TY '/5'],'autorouting','on');
add_line(name,'Prs/1',                          [TY '/6'],'autorouting','on');
if ~useVDB
    add_line(name,sprintf('%s/%d',PRE,pOut.Fz), [TY '/7'],'autorouting','on');   % Fext
end   % the VDB build drives Fext from the suspension block's own WhlF
add_line(name,'Gnd/1',                          [TY '/8'],'autorouting','on');
add_line(name,sprintf('%s/%d',PRE,pOut.muScale),[TY '/9'],'autorouting','on');

% tyre outputs: Info, Omega, Fx, Fy, Fz, Mx, My, Mz
add_line(name,[TY '/1'],'Info/1','autorouting','on');
add_line(name,[TY '/2'],'wheel omega (delay)/1','autorouting','on');
add_line(name,[TY '/3'],sprintf('%s/1',POST),'autorouting','on');   % Fx
add_line(name,[TY '/4'],sprintf('%s/2',POST),'autorouting','on');   % Fy
add_line(name,[TY '/5'],sprintf('%s/3',POST),'autorouting','on');   % Fz
add_line(name,[TY '/2'],sprintf('%s/4',POST),'autorouting','on');   % Omega
add_line(name,sprintf('%s/%d',PRE,pOut.steer_o),sprintf('%s/5',POST),'autorouting','on');
add_line(name,sprintf('%s/%d',PRE,pOut.Vxw),    sprintf('%s/6',POST),'autorouting','on');
add_line(name,sprintf('%s/%d',PRE,pOut.Vyw),    sprintf('%s/7',POST),'autorouting','on');

% Wheels bus: omega, steer, fz, fx, fy, slip_ratio, slip_angle, susp_travel, in_contact
add_line(name,sprintf('%s/1',POST),'Wheels Bus/1','autorouting','on');   % omega
% Named explicitly: the bus object calls this element 'steer' but the function
% output is 'steer_o', and an unnamed line makes Simulink warn on every compile.
lh = add_line(name,sprintf('%s/%d',PRE,pOut.steer_o),'Wheels Bus/2','autorouting','on');
set_param(lh,'Name','steer');
add_line(name,sprintf('%s/2',POST),'Wheels Bus/3','autorouting','on');   % fz
add_line(name,sprintf('%s/3',POST),'Wheels Bus/4','autorouting','on');   % fx
add_line(name,sprintf('%s/4',POST),'Wheels Bus/5','autorouting','on');   % fy
add_line(name,sprintf('%s/5',POST),'Wheels Bus/6','autorouting','on');   % slip_ratio
add_line(name,sprintf('%s/6',POST),'Wheels Bus/7','autorouting','on');   % slip_angle
add_line(name,sprintf('%s/%d',PRE,pOut.susp_travel),'Wheels Bus/8','autorouting','on');
add_line(name,sprintf('%s/%d',PRE,pOut.in_contact), 'Wheels Bus/9','autorouting','on');
add_line(name,sprintf('%s/7',POST),'tyre_force/1','autorouting','on');
add_line(name,sprintf('%s/8',POST),'tyre_torque/1','autorouting','on');
add_line(name,[TY '/6'],'Mx/1','autorouting','on');
add_line(name,[TY '/7'],'My/1','autorouting','on');
add_line(name,[TY '/8'],'Mz/1','autorouting','on');

save_system(name,f);
fprintf('wrote %s\n',f);
fprintf('  MF 6.2 tyre: %d coefficients written, mu %.2f, Ca %.0f N/rad, Fz0 %.0f N\n', ...
        nset, TP.PDY1, ...
        -TP.PKY1*TP.FNOMIN*sin(TP.PKY4*atan(1/TP.PKY2)), TP.FNOMIN);
fprintf('  suspension: wheel rate %.0f N/m, damping %.0f N.s/m\n', ...
        P.Derived.WheelRateEach, P.Derived.SuspensionDampingCoeff);
close_system(name,0);
end

%% =======================================================================
function set_sizes(chart, sizes)
data = chart.find('-isa','Stateflow.Data');
for k = 1:numel(data)
    d = data(k);
    if isfield(sizes,d.Name), d.Props.Array.Size = mat2str(sizes.(d.Name)); end
end
end

function add_params(chart, params)
data = chart.find('-isa','Stateflow.Data');
existing = {data.Name};
for k = 1:numel(params)
    if any(strcmp(existing,params{k})), continue; end
    d = Stateflow.Data(chart);
    d.Name = params{k}; d.Scope = 'Parameter'; d.Props.Array.Size = '1';
end
end

%% =======================================================================
function c = pre_code()
L = {
"function [Fz, Vxw, Vyw, AxlTrq, steer_o, susp_travel, in_contact, muScale, camber, WhlPz, WhlVz] = ..."
"         tiresusp_pre(road_valid, road_h, road_mu, road_res, pos, quat, velb, omegab, steer_in, drive_t, brake_t, w_fb)"
"%#codegen"
"% Suspension load and contact-patch kinematics for four corners, plus the"
"% axle torque that drives the tyre block."
"%"
"% Wheel order FL, FR, RL, RR. Body frame ISO 8855: x forward, y LEFT, z up."
""
"Rw = IFSSIM_Rw;"
""
"% Wheel positions in the body frame, at CoG height. y is POSITIVE LEFT, so the"
"% left wheels take +track/2. Getting this backwards mirrors the car and is"
"% almost impossible to see in a lap time."
"rx = [ IFSSIM_aF;  IFSSIM_aF; -IFSSIM_bR; -IFSSIM_bR];"
"ry = [ IFSSIM_tF/2; -IFSSIM_tF/2;  IFSSIM_tR/2; -IFSSIM_tR/2];"
"Fz_static = [IFSSIM_FzF; IFSSIM_FzF; IFSSIM_FzR; IFSSIM_FzR];"
""
"q = quat / max(norm(quat), eps);"
"R = q2r(q);                      % body -> world"
"vel_world   = R * velb;"
"omega_world = R * omegab;"
""
"Fz      = zeros(4,1);  Vxw     = zeros(4,1);  Vyw        = zeros(4,1);"
"AxlTrq  = zeros(4,1);  steer_o = zeros(4,1);  susp_travel= zeros(4,1);"
"camber  = zeros(4,1);"
"% What the VDB suspension block wants, if it is in the model: displacement"
"% from the static ride position in a z-DOWN frame, so positive is droop and"
"% our compression-positive delta is its negative. Measured, see"
"% docs/vdb_step1_port_semantics.md -- feeding it a ride height instead of a"
"% displacement is what made the first attempt return 2568 N a wheel."
"WhlPz   = zeros(4,1);  WhlVz = zeros(4,1);"
"in_contact = zeros(4,1);  muScale = ones(27,4);"
""
"% ---- suspension deflection, all four corners at once ----------------"
"% This has to be a separate pass. An anti-roll bar reacts the DIFFERENCE in"
"% deflection across an axle, so no corner's vertical load can be known until"
"% both corners of its axle are."
"delta  = zeros(4,1);"
"ddelta = zeros(4,1);"
"for i = 1:4"
"    r_w = R * [rx(i); ry(i); 0];"
"    p_w = pos + r_w;                      % corner position, world"
"    % delta > 0 means compressed relative to static ride height."
"    gap       = p_w(3) - (road_h(i) + Rw);    % attachment above wheel centre"
"    delta(i)  = IFSSIM_L0 - gap;"
"    % Compression RATE is the downward velocity of this corner. Using the"
"    % corner velocity rather than the CoG velocity is what makes roll and"
"    % pitch damping appear at all."
"    v_corner  = vel_world + cross(omega_world, r_w);"
"    ddelta(i) = -v_corner(3);"
"end"
""
"% ---- anti-roll bars -------------------------------------------------"
"% A bar carries K_arb times the roll angle of its axle, delivered as a force"
"% couple across the track: dF = K_arb*(dL - dR)/t^2, up on the compressed"
"% side and down on the other, summing to zero so it adds no heave stiffness."
"%"
"% These are not a detail. They are the ONLY thing that makes the front and"
"% rear roll stiffnesses differ, and that difference is the car's balance."
"% With four equal springs and equal tracks -- which is what this model had --"
"% lateral load transfer splits exactly 50.0/50.0 at every steer angle and"
"% nothing can move it, so the car can be neither understeering nor"
"% oversteering by construction. See ifssim_params for how the bar rates come"
"% out of RollStiffnessFront/Rear, which until now were read by nothing."
"arbF = IFSSIM_arbF * (delta(1) - delta(2)) / (IFSSIM_tF*IFSSIM_tF);"
"arbR = IFSSIM_arbR * (delta(3) - delta(4)) / (IFSSIM_tR*IFSSIM_tR);"
"arb  = [arbF; -arbF; arbR; -arbR];"
""
"% ---- camber -----------------------------------------------------------"
"% Inclination each tyre sees: its static setting, plus the share of body roll"
"% the geometry does NOT take back out. Camber gain 1.0 keeps the wheel"
"% upright through the corner; a real double wishbone falls short of that."
"%"
"% Roll comes from the quaternion the chassis already integrates, so this is"
"% the roll the car ACTUALLY has -- not the algebraic estimate the design"
"% model has to make. That is the one place the plant is now ahead of it."
"%"
"% It is wired to the tyre block's Camber input, which this model used to hold"
"% at a constant zero. The tyre does not yet RESPOND to it: the camber"
"% coefficients in the Magic Formula set are zeroed, because nobody has put"
"% this tyre on a rig and inventing PDY3 would be inventing grip. The"
"% kinematics are real and arrive at the tyre; the tyre's answer to them is"
"% the part still waiting on data."
"%"
"% The two terms mirror DIFFERENTLY, and getting that backwards is the easy"
"% mistake. In the ISO tyre axis system y points left on BOTH wheels, so:"
"%"
"%   static camber is symmetric in space -- the tops lean toward each other --"
"%   and therefore reads with OPPOSITE sign on the two sides (sgnOut);"
"%"
"%   roll tilts both wheels the SAME way in space, so it reads with the SAME"
"%   sign on both, and must stay OUTSIDE the mirror."
"%"
"% This used to apply the static setting uniformly to all four and mirror the"
"% roll term -- exactly inverted, on both counts. It changed no force, because"
"% the camber coefficients are zeroed, and it would have changed every one of"
"% them the day rig data arrives. The structure here is not argued from the"
"% convention: it is what the VDB double-wishbone block measurably does"
"% (see vdb_camber_mask), and the two now agree to 3e-10 deg."
"%"
"% The OVERALL SIGN of gamma is still unpinned. Nothing in this plant can"
"% settle it while the Magic Formula camber terms are zero -- there is no"
"% observable to check it against. It wants fixing against rig data, not"
"% against an argument."
"rollAng = atan2(2*(q(1)*q(2) + q(3)*q(4)), 1 - 2*(q(2)*q(2) + q(3)*q(3)));"
"sgnOut  = [-1; 1; -1; 1];"
"camber  = sgnOut .* [IFSSIM_camF; IFSSIM_camF; IFSSIM_camR; IFSSIM_camR] + ..."
"          (1 - [IFSSIM_cgainF; IFSSIM_cgainF; IFSSIM_cgainR; IFSSIM_cgainR]) * rollAng;"
""
"for i = 1:4"
"    r_b = [rx(i); ry(i); 0];"
"    r_w = R * r_b;"
"    p_w = pos + r_w;                      % corner position, world"
""
"    kw_i = IFSSIM_kwF; if i > 2, kw_i = IFSSIM_kwR; end"
"    Fz_i = Fz_static(i) + kw_i * delta(i) + IFSSIM_cw * ddelta(i) + arb(i);"
""
"    % A tyre cannot pull the road. Clamping here is what lets a wheel lift"
"    % in a corner instead of generating negative grip."
"    if Fz_i < 0, Fz_i = 0; end"
"    % Contact needs the platform to have actually CHARACTERISED the ground,"
"    % not merely to have hit something with one ray."
"    %"
"    % A NEGATIVE residual is the platform saying it could not fit a plane at"
"    % all - fewer than three of its rays hit - so it does not know what is"
"    % under this wheel. Standing on an answer nobody has is how a wheel ends"
"    % up loaded against geometry that is not there."
"    %"
"    % A LARGE residual is a different thing entirely and deliberately does NOT"
"    % remove contact. It means the patch spans a step or a kerb edge: the"
"    % ground is poorly described by a plane, but the tyre is still touching"
"    % it. Dropping Fz there would make the car fall through every kerb, which"
"    % is worse than the flat-plane approximation it would be replacing."
"    fit_known = (road_res(i) >= 0);"
"    contact = (road_valid(i) > 0.5) && (Fz_i > 0) && fit_known;"
"    if ~contact, Fz_i = 0; end"
""
"    % ---- contact-patch velocity ------------------------------------"
"    v_b = velb + cross(omegab, r_b);"
"    d   = steer_in(i);"
"    cd  = cos(d); sd = sin(d);"
"    vx =  v_b(1)*cd + v_b(2)*sd;          % along the wheel"
"    vy = -v_b(1)*sd + v_b(2)*cd;          % across it"
""
"    % ---- axle torque -----------------------------------------------"
"    % The tyre block's own brake and rolling-resistance models are switched"
"    % off, so both arrive here as torque on the axle instead."
"    %"
"    % w_fb is last step's wheel speed, delayed. Using it rather than the"
"    % block's live Omega is what keeps this out of an algebraic loop; at"
"    % 1/960 s the wheel cannot turn far enough in one step for the"
"    % difference to matter."
"    %"
"    % tanh, not sign: sign() chatters about zero every step at 1/960 s. tanh"
"    % also means both torques fade smoothly to zero as the wheel stops, so"
"    % they RESIST motion but cannot HOLD a stopped car - arresting creep"
"    % entirely needs a stiction term, which this is not."
"    % Smoothed over IFSSIM_wreg, which is deliberately WIDER than the wheel"
"    % speed one step of brake torque can produce. Narrower than that and this"
"    % is sign() in all but name, and the stop ends in a limit cycle."
"    dirw    = tanh(w_fb(i) / IFSSIM_wreg);"
"    % LOCK, DO NOT REVERSE. Brake torque is a magnitude opposing rotation, so"
"    % it must never be large enough to drive the wheel backwards through zero."
"    % The old hand-written tyre clamped the wheel state directly after"
"    % integrating; wheel spin now lives inside the tyre block, where we cannot"
"    % reach it, so the limit has to be applied to the TORQUE instead."
"    %"
"    % Iw*|w|/Ts is exactly the torque that brings this wheel to rest in one"
"    % step. Anything beyond it would reverse the wheel, which a brake cannot"
"    % do: at 286 N.m on Iw = 0.21 one step moves the wheel 1.4 rad/s, so"
"    % without this the EBS walks a stopping wheel backwards through zero."
"    T_cap   = IFSSIM_Iw * abs(w_fb(i)) / IFSSIM_Ts;"
"    T_brake = min(brake_t(i), T_cap) * dirw;"
"    % Rolling resistance. Physically the contact patch's pressure"
"    % distribution shifts forward of the axle and the resulting moment"
"    % opposes rotation. Modelling it as a drag force on the chassis would"
"    % give a similar top speed and the wrong wheel dynamics."
"    T_roll  = IFSSIM_Crr * Fz_i * Rw * dirw;"
"    AxlTrq(i) = drive_t(i) - T_brake - T_roll;"
""
"    % ---- friction scaling ------------------------------------------"
"    % The tyre carries one set of coefficients, but the road can differ under"
"    % each wheel. Magic Formula takes a column of 27 SCALING FACTORS per"
"    % wheel, and two of them scale peak friction; everything else stays 1."
"    %"
"    % Indices 3 and 10 are LMUX and LMUY in the standard Magic Formula"
"    % ordering. That ordering is not documented on the block and the code"
"    % behind it is P-coded, so it was checked instead of assumed: perturbing"
"    % each of the 27 in turn, 19 and 20 moved the combined-slip coupling,"
"    % which is exactly where the standard order puts LXAL and LYKA, and 3"
"    % scaled lateral grip directly in a pure-slip test. Both mu factors are"
"    % set to the same ratio, so a road reporting the nominal mu scales by 1."
"    muw = road_mu(i);"
"    if muw <= 0, muw = IFSSIM_mu; end"
"    mur = muw / IFSSIM_mu;"
"    muScale(3,i)  = mur;"
"    muScale(10,i) = mur;"
""
"    Fz(i)=Fz_i; Vxw(i)=vx; Vyw(i)=vy; steer_o(i)=d;"
"    susp_travel(i)=delta(i); in_contact(i)=double(contact);"
"    WhlPz(i) = -delta(i);  WhlVz(i) = -ddelta(i);"
"end"
"end"
""
"function R = q2r(q)"
"%#codegen"
"w=q(1); x=q(2); y=q(3); z=q(4);"
"R = [1-2*(y*y+z*z),   2*(x*y-z*w),   2*(x*z+y*w); ..."
"       2*(x*y+z*w), 1-2*(x*x+z*z),   2*(y*z-x*w); ..."
"       2*(x*z-y*w),   2*(y*z+x*w), 1-2*(x*x+y*y)];"
"end"
};
c = char(strjoin(string(L), newline));
end

%% =======================================================================
function c = post_code()
L = {
"function [omega, fz, fx, fy, slip_ratio, slip_angle, tyre_force, tyre_torque] = ..."
"         tiresusp_post(Fx_in, Fy_in, Fz_in, Om, steer_in, Vxw, Vyw)"
"%#codegen"
"% Four wheel forces, in their own wheel frames, assembled into one body-frame"
"% wrench -- plus the reported per-wheel state."
""
"rx = [ IFSSIM_aF;  IFSSIM_aF; -IFSSIM_bR; -IFSSIM_bR];"
"ry = [ IFSSIM_tF/2; -IFSSIM_tF/2;  IFSSIM_tR/2; -IFSSIM_tR/2];"
"Rw = IFSSIM_Rw;"
""
"omega = reshape(Om,    4, 1);"
"fx    = reshape(Fx_in, 4, 1);"
"fy    = reshape(Fy_in, 4, 1);"
"fz    = reshape(Fz_in, 4, 1);"
""
"slip_ratio = zeros(4,1);  slip_angle = zeros(4,1);"
"F_sum = zeros(3,1);       M_sum      = zeros(3,1);"
""
"for i = 1:4"
"    % Slip is REPORTED here, not used. The tyre block computes its own"
"    % internally, with relaxation; this is the algebraic value, recomputed"
"    % for telemetry so the bus still carries the quantity it always did."
"    vref = max(abs(Vxw(i)), IFSSIM_vreg);"
"    slip_ratio(i) = (omega(i)*Rw - Vxw(i)) / vref;"
"    slip_angle(i) = atan2(Vyw(i), vref);"
""
"    % Wheel frame -> body frame. Fx acts along the wheel, Fy across it, and"
"    % the wheel is rotated by the steer angle relative to the body."
"    d  = steer_in(i);"
"    cd = cos(d); sd = sin(d);"
"    Fb = [fx(i)*cd - fy(i)*sd; fx(i)*sd + fy(i)*cd; fz(i)];"
"    F_sum = F_sum + Fb;"
""
"    % The tyre force acts at the CONTACT PATCH, on the road, not at the CoG."
"    % That arm IS load transfer: it is what turns a lateral force into a roll"
"    % moment and a longitudinal force into a pitch moment."
"    %"
"    % This used to be [rx; ry; 0], and the reason it survived so long is that"
"    % a zero z still gives the RIGHT answer for three of the six terms. Yaw"
"    % (rx*fy - ry*fx) has no z in it at all, and the roll and pitch from the"
"    % VERTICAL loads (ry*fz, -rx*fz) do not either. So the car rolled"
"    % correctly whenever something else rolled it -- which is every test that"
"    % imposes a body rate. What it could not do was roll ITSELF: the two"
"    % missing terms, -rz*fy and +rz*fx, are precisely the ones by which the"
"    % tyres act on the body. Measured before the fix: 0.000000 rad of roll in"
"    % a 1.2 g corner, and load transfer at 0.1% of what m*a*h/t requires."
"    %"
"    % Taking the arm all the way to the ground puts the roll centre at ground"
"    % level, so every newton of lateral transfer goes through the springs and"
"    % none through the suspension links. That is a real assumption and it is"
"    % stated here rather than hidden: this model HAS no links -- no wishbones,"
"    % no instantaneous centres -- so a non-zero roll centre would not be a"
"    % better number, it would be an invented one. It costs less than it"
"    % sounds: the TOTAL transfer is m*a*h/t whatever the roll centre does."
"    % What a real one would change is the elastic/geometric split, and with"
"    % it the roll ANGLE and the transient, not the steady-state load split."
"    %"
"    % The height is held constant at the static CoG height. Tracking ride"
"    % height through suspension travel would be a centimetre of correction on"
"    % a 34 cm arm, sitting on top of a CoG height nobody has measured."
"    M_sum = M_sum + cross([rx(i); ry(i); -IFSSIM_CoGH], Fb);"
"end"
""
"tyre_force  = F_sum;"
"tyre_torque = M_sum;"
"end"
};
c = char(strjoin(string(L), newline));
end

% -------------------------------------------------------------------------
function tag_camber_probe(name, TY)
%TAG_CAMBER_PROBE  Log whatever reaches the tyre's Camber input.
%
%   The camber coefficients in the Magic Formula set are zeroed (no rig
%   data), so camber changes NO force -- which means no wrench comparison
%   can tell a correct camber path from a severed one. vdb_step2_check
%   found exactly that: it passed a mutant. The signal itself is therefore
%   the only honest observable, so it is named and logged here.
lh = get_param([name '/' TY],'LineHandles');
set_param(lh.Inport(4),'Name','camber_at_tyre');
% Logging lives on the SOURCE PORT, not on the line -- lines carry only the
% name. Setting it on the line fails with "no parameter named DataLogging".
set_param(get_param(lh.Inport(4),'SrcPortHandle'), ...
          'DataLogging','on','DataLoggingNameMode','SignalName');
set_param(name,'SignalLogging','on','SignalLoggingName','tsLog');
end

% -------------------------------------------------------------------------
function tag_probe(name, blk, port, signame)
%TAG_PROBE  Name and log one output port, so a check can read it by name.
%
%   Same reason as tag_camber_probe: the quantity being verified has to be
%   observable. Logging both the block's force and ours in the SAME run beats
%   comparing across two builds -- there is no second build to drift.
ph = get_param([name '/' blk],'PortHandles');
set_param(ph.Outport(port),'DataLogging','on', ...
          'DataLoggingNameMode','Custom','DataLoggingName',signame);
set_param(name,'SignalLogging','on','SignalLoggingName','tsLog');
end
