function build_chassis(outdir)
%BUILD_CHASSIS  Fill in IFSSIM_Chassis: 6-DOF rigid-body dynamics.
%
%   6-DOF rigid body. Everything else feeds it forces; this integrates them.
%
%     forces --> [Rigid Body Update] --> next state --> [Unit Delay] --+
%                                    \--> Pose bus out                 |
%                        state ---------------------------------------+
%
%   State is in Unit Delays so it is visible on the canvas. The update reads
%   LAST step's state, so there is no algebraic loop by construction.

if nargin < 1 || isempty(outdir)
    outdir = fullfile(fileparts(mfilename('fullpath')), 'models');
end
addpath(fileparts(mfilename('fullpath'))); addpath(outdir);

P = ifssim_load_workspace();

name = 'IFSSIM_Chassis';
if bdIsLoaded(name), close_system(name,0); end
f = fullfile(outdir,[name '.slx']);
if isfile(f), delete(f); end

new_system(name,'Model');
set_param(name,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
               'FixedStep','1/960','StartTime','0','StopTime','inf');

%% ---- inputs -----------------------------------------------------------
ins = {'tyre_force',3; 'tyre_torque',3; 'aero_force',3; 'aero_torque',3};
y = 40;
for i = 1:size(ins,1)
    b = [name '/' ins{i,1}];
    add_block('simulink/Sources/In1', b, 'Position',[30 y 60 y+20], ...
              'PortDimensions',num2str(ins{i,2}));
    y = y + 60;
end
add_block('simulink/Sources/In1',[name '/Env'],'Position',[30 y 60 y+20], ...
          'OutDataTypeStr','Bus: IFSSIM_EnvBus','BusOutputAsStruct','on');

% Split Env here rather than inside the function. The selector documents which
% fields the chassis actually uses, and it keeps struct typing out of a block
% that only wants numbers.
add_block('simulink/Signal Routing/Bus Selector',[name '/Env Select'], ...
          'Position',[140 y-20 150 y+80], ...
          'OutputSignals','gravity_z,ext_force,ext_torque');
add_line(name,'Env/1','Env Select/1','autorouting','on');

y = y + 60;
add_block('simulink/Sources/In1',[name '/Sync'],'Position',[30 y 60 y+20], ...
          'OutDataTypeStr','Bus: IFSSIM_SyncBus','BusOutputAsStruct','on');

% Same treatment for Sync. Splitting it here keeps the state-injection fields
% visible on the canvas: someone opening this model can see that the platform
% is able to write pose, which a struct passed whole into a function would hide.
add_block('simulink/Signal Routing/Bus Selector',[name '/Sync Select'], ...
          'Position',[140 y+120 150 y+230], ...
          'OutputSignals','enable,pos,quat,vel_body,omega_body');
add_line(name,'Sync/1','Sync Select/1','autorouting','on');

%% ---- the update function ---------------------------------------------
fcn = [name '/Rigid Body Update'];
add_block('simulink/User-Defined Functions/MATLAB Function', fcn, ...
          'Position',[260 40 460 320]);

code = chassis_code();
S = sfroot;
chart = S.find('-isa','Stateflow.EMChart','Path',fcn);
chart.Script = code;

% EXPLICIT PORT SIZES. Without these the model does not compile, and the error
% is not obvious: the function cannot infer its input sizes because they come
% from the Unit Delays, whose sizes come from the function's own outputs. That
% circle has no fixed point until someone states a dimension.
%
% Declaring every port also makes the block self-documenting — the contract is
% visible in the Ports and Data Manager, not only in the signature.
sizes = struct( ...
    'tyre_f',3,      'tyre_t',3,     'aero_f',3,       'aero_t',3, ...
    'gravity_z',1,   'ext_force',3,  'ext_torque',3, ...
    'pos_i',3,       'quat_i',4,     'velb_i',3,       'omega_i',3, ...
    'sync_en',1,     'sync_pos',3,   'sync_quat',4,    'sync_velb',3, 'sync_omega',3, ...
    'pos_n',3,       'quat_n',4,     'velb_n',3,       'omega_n',3, ...
    'position',3,    'quat',4,       'vel_world',3,    'vel_body',3, ...
    'omega_body',3,  'alpha_body',3, 'accel_proper',3, 'attitude',3);

data = chart.find('-isa','Stateflow.Data');
for k = 1:numel(data)
    d = data(k);
    if isfield(sizes, d.Name)
        d.Props.Array.Size = num2str(sizes.(d.Name));
    end
end

% PARAMETERS must be DECLARED, not merely present in the base workspace.
% A MATLAB Function block does not pick up workspace variables the way a plain
% script does — an undeclared IFSSIM_Mass is simply an unknown identifier, and
% the resulting compile error says only "errors in the block body", which sends
% you looking at the maths instead of at the data dictionary.
%
% Declared this way, Simulink resolves each one from the base workspace at
% compile time, where ifssim_load_workspace() has put it — from settings.json.
params = {'IFSSIM_Ts','IFSSIM_Mass','IFSSIM_Ixx','IFSSIM_Iyy','IFSSIM_Izz','IFSSIM_CoGH'};
existing = {data.Name};
for k = 1:numel(params)
    if any(strcmp(existing, params{k})), continue; end
    d = Stateflow.Data(chart);
    d.Name  = params{k};
    d.Scope = 'Parameter';
    d.Props.Array.Size = '1';
end

%% ---- state memory -----------------------------------------------------
% Initial conditions: at rest, level, at the origin. The platform teleports the
% car to the start gate by writing pose, so a non-zero IC here would just be a
% number to forget to update.
% Start AT RIDE HEIGHT, not at the world origin. With pos = [0;0;0] the corner
% attachments sit level with the road, so the suspension reads 0.3 m of
% compression on the first step and fires the car into the air. The platform
% teleports the car to the start gate anyway, but a plant that cannot be started
% from its own defaults is a plant nobody can test in isolation.
states = {'pos',      '[0;0;IFSSIM_CoGH]'
          'quat',     '[1;0;0;0]'
          'vel_body', '[0;0;0]'
          'omega',    '[0;0;0]'};
y = 400;
for i = 1:size(states,1)
    b = [name '/' states{i,1} ' (state)'];
    add_block('simulink/Discrete/Unit Delay', b, ...
              'Position',[300 y 360 y+30], 'InitialCondition',states{i,2}, ...
              'SampleTime','-1');
    y = y + 60;
end

%% ---- outputs ----------------------------------------------------------
add_block('simulink/Signal Routing/Bus Creator',[name '/Pose Bus'], ...
          'Position',[560 40 570 320], 'Inputs','8', ...
          'OutDataTypeStr','Bus: IFSSIM_PoseBus', ...
          'NonVirtualBus','on');
add_block('simulink/Sinks/Out1',[name '/Pose'],'Position',[640 170 670 190], ...
          'OutDataTypeStr','Bus: IFSSIM_PoseBus');
add_line(name,'Pose Bus/1','Pose/1','autorouting','on');

%% ---- wiring -----------------------------------------------------------
% Function port order follows the script signature exactly. Getting this wrong
% is silent — every signal is a double vector, so a swapped pair type-checks
% perfectly and simply produces a different car.
FB = 'Rigid Body Update';

% inputs 1..5: tyre_f, tyre_t, aero_f, aero_t, env
srcIn = {'tyre_force','tyre_torque','aero_force','aero_torque'};
for i = 1:numel(srcIn)
    add_line(name, [srcIn{i} '/1'], sprintf('%s/%d', FB, i), 'autorouting','on');
end
% inputs 5..7 come off the Env selector, in its declared output order.
for i = 1:3
    add_line(name, sprintf('Env Select/%d', i), sprintf('%s/%d', FB, 4+i), 'autorouting','on');
end

% inputs 8..11 are LAST step's state, read back from the delays. This is what
% breaks the algebraic loop: the update never reads its own current output.
stateNames = {'pos','quat','vel_body','omega'};
for i = 1:numel(stateNames)
    add_line(name, [stateNames{i} ' (state)/1'], sprintf('%s/%d', FB, 7+i), 'autorouting','on');
end

% inputs 12..16 come off the Sync selector, in its declared output order.
for i = 1:5
    add_line(name, sprintf('Sync Select/%d', i), sprintf('%s/%d', FB, 11+i), 'autorouting','on');
end

% outputs 1..4 are the NEXT state, fed into the delays.
for i = 1:numel(stateNames)
    add_line(name, sprintf('%s/%d', FB, i), [stateNames{i} ' (state)/1'], 'autorouting','on');
end

% outputs 5..12 are the reported state, in IFSSIM_PoseBus element order:
% position, quat, vel_world, vel_body, omega_body, alpha_body, accel_proper, attitude
for i = 1:8
    add_line(name, sprintf('%s/%d', FB, 4+i), sprintf('Pose Bus/%d', i), 'autorouting','on');
end

save_system(name, f);
fprintf('wrote %s\n', f);
fprintf('  mass %.0f kg, inertia [%.0f %.0f %.0f] kg m^2 (ASSUMED)\n', ...
        P.Mass, P.Assumed.Ixx, P.Assumed.Iyy, P.Assumed.Izz);
close_system(name,0);
end

%% =======================================================================
function c = chassis_code()
c = sprintf('%s\n', ...
"function [pos_n, quat_n, velb_n, omega_n, position, quat, vel_world, vel_body, omega_body, alpha_body, accel_proper, attitude] = ...", ...
"         chassis(tyre_f, tyre_t, aero_f, aero_t, gravity_z, ext_force, ext_torque, pos_i, quat_i, velb_i, omega_i, ...", ...
"                 sync_en, sync_pos, sync_quat, sync_velb, sync_omega)", ...
"%#codegen", ...
"% 6-DOF rigid body, Newton-Euler in the body frame, forward Euler at Ts.", ...
"%", ...
"% Frames: body is ISO 8855 / REP-103 — x forward, y LEFT, z up. World is ENU.", ...
"% Wheel order elsewhere is FL, FR, RL, RR.", ...
"%", ...
"% tyre_f / aero_f arrive in the BODY frame (they are generated by body-attached", ...
"% things). ext_force is WORLD — it comes from the platform's collision solver,", ...
"% which has no opinion about the car's orientation.", ...
"%", ...
"% The Env bus is split by a Bus Selector OUTSIDE this block rather than passed", ...
"% in whole. Two reasons: a MATLAB Function block has to infer a struct type", ...
"% through the port, which is fragile; and the selector makes the diagram show", ...
"% exactly which Env fields the chassis consumes.", ...
"", ...
"% Flat workspace scalars, not IFSSIM_P.Assumed.Izz: a MATLAB Function block", ...
"% resolves workspace variables as parameters and that lookup does not reach", ...
"% into nested structs. See ifssim_load_workspace.m — still one source, still", ...
"% settings.json.", ...
"Ts = IFSSIM_Ts;", ...
"m  = IFSSIM_Mass;", ...
"I  = [IFSSIM_Ixx; IFSSIM_Iyy; IFSSIM_Izz];   % principal, diagonal", ...
"", ...
"% --- state injection -------------------------------------------------", ...
"% Applied to the INCOMING state, before any dynamics. Overriding the outgoing", ...
"% state instead would look equivalent and is not: this step would still", ...
"% compute its forces and its reported acceleration from the OLD pose, so the", ...
"% caller would read a response to a state the plant is no longer in. For a", ...
"% one-step comparison against a reference that is precisely the wrong answer,", ...
"% and it is wrong by one step, which is the hardest kind of wrong to see.", ...
"%", ...
"% Normal running leaves enable at zero and nothing here executes.", ...
"if sync_en > 0.5", ...
"    pos_i   = sync_pos;", ...
"    quat_i  = sync_quat / max(norm(sync_quat), eps);", ...
"    velb_i  = sync_velb;", ...
"    omega_i = sync_omega;", ...
"end", ...
"", ...
"% --- orientation ---------------------------------------------------", ...
"q = quat_i / max(norm(quat_i), eps);        % renormalise every step: forward Euler", ...
"                                        % on a quaternion drifts off the unit", ...
"                                        % sphere, and the drift is silent.", ...
"R = quat2rotm_local(q);                 % body -> world", ...
"", ...
"% --- forces ----------------------------------------------------------", ...
"% Everything to the body frame first, then one sum. Mixing frames in a", ...
"% force accumulator is the classic way to get a plausible-but-wrong plant.", ...
"F_body = tyre_f + aero_f + R' * ext_force;", ...
"M_body = tyre_t + aero_t + R' * ext_torque;", ...
"", ...
"% PROPER acceleration excludes gravity — it is what an accelerometer reads.", ...
"% Publishing this directly is the point: the simulator currently finite-", ...
"% differences a world velocity and bolts +g on, which is where the missing", ...
"% Coriolis terms in the EKF came from.", ...
"accel_proper = F_body / m;", ...
"", ...
"% Gravity acts on the body but is NOT felt by an accelerometer, so it enters", ...
"% the equation of motion after accel_o has been taken.", ...
"g_body = R' * [0; 0; gravity_z];", ...
"", ...
"% --- rigid body ------------------------------------------------------", ...
"% v_dot = F/m + g - omega x v      (Coriolis term: body-frame rates are not", ...
"%                                   inertial, and dropping this is exactly the", ...
"%                                   bug that made vy drift during cornering)", ...
"vdot  = accel_proper + g_body - cross(omega_i, velb_i);", ...
"", ...
"% I*omega_dot = M - omega x (I*omega)   (gyroscopic coupling)", ...
"Iw    = I .* omega_i;", ...
"alpha_body = (M_body - cross(omega_i, Iw)) ./ I;", ...
"", ...
"% --- integrate -------------------------------------------------------", ...
"velb_n  = velb_i + Ts * vdot;", ...
"omega_n = omega_i + Ts * alpha_body;", ...
"", ...
"% Position integrates the WORLD velocity.", ...
"vel_world = R * velb_i;", ...
"pos_n   = pos_i + Ts * vel_world;", ...
"", ...
"% q_dot = 0.5 * q (x) [0; omega]", ...
"qd      = 0.5 * quatmul_local(q, [0; omega_i]);", ...
"quat_n  = q + Ts * qd;", ...
"quat_n  = quat_n / max(norm(quat_n), eps);", ...
"", ...
"% --- reported state ---------------------------------------------------", ...
"position = pos_i;", ...
"quat    = q;", ...
"vel_body = velb_i;", ...
"omega_body = omega_i;", ...
"", ...
"% attitude = [roll; pitch; heave]. Heave is height above the declared static", ...
"% CoG height, so 0 means sitting at ride height rather than at the world origin.", ...
"roll_  = atan2(2*(q(1)*q(2) + q(3)*q(4)), 1 - 2*(q(2)^2 + q(3)^2));", ...
"sinp   = 2*(q(1)*q(3) - q(4)*q(2));", ...
"pitch_ = asin(max(-1, min(1, sinp)));", ...
"attitude = [roll_; pitch_; pos_i(3) - IFSSIM_CoGH];", ...
"end", ...
"", ...
"function R = quat2rotm_local(q)", ...
"%#codegen", ...
"w = q(1); x = q(2); y = q(3); z = q(4);", ...
"R = [1-2*(y*y+z*z),   2*(x*y-z*w),   2*(x*z+y*w); ...", ...
"       2*(x*y+z*w), 1-2*(x*x+z*z),   2*(y*z-x*w); ...", ...
"       2*(x*z-y*w),   2*(y*z+x*w), 1-2*(x*x+y*y)];", ...
"end", ...
"", ...
"function r = quatmul_local(a, b)", ...
"%#codegen", ...
"r = [a(1)*b(1) - a(2)*b(2) - a(3)*b(3) - a(4)*b(4); ...", ...
"     a(1)*b(2) + a(2)*b(1) + a(3)*b(4) - a(4)*b(3); ...", ...
"     a(1)*b(3) - a(2)*b(4) + a(3)*b(1) + a(4)*b(2); ...", ...
"     a(1)*b(4) + a(2)*b(3) - a(3)*b(2) + a(4)*b(1)];", ...
"end");
end

