function ok = test_validate_vs_car()
%TEST_VALIDATE_VS_CAR  Prove the car-validation harness can tell right from wrong.
%
%   There is no real-car data in this repo -- every recording under
%   tools/vd_validation/data is from the simulator, and all of them crawl. So
%   the harness cannot yet be checked against the car. It CAN be checked
%   against a car whose answer is known: a synthetic run generated by the
%   design model itself, written out as a CSV in exactly the format
%   bag_to_vd_csv.py produces, then pushed back through the whole pipeline.
%
%   Two properties, and a harness without both is worse than none:
%
%   IDENTITY. Replaying a run into the model that generated it must score
%   close to perfect. If it does not, the plumbing is wrong -- misaligned
%   clocks, a units slip, a filter that shifts the signal -- and every number
%   it ever reports against the real car is contaminated by that error.
%
%   DISCRIMINATION. Replaying into a DIFFERENT model must score clearly worse.
%   A harness that reports a good fit for the wrong model is the vacuous-gate
%   failure this project has already hit twice. The thresholds below were
%   fixed before the first run, not chosen afterwards to make it pass.
%
%   The synthetic measurement is deliberately made dirty in the ways real
%   data is: sensor noise, and a few physically impossible IMU spikes like the
%   -160 m/s^2 sample found in a recorded run.

here = fileparts(mfilename('fullpath'));
addpath(here, fullfile(here,'..','plant'), fullfile(here,'..','spec'));
ok = true;
fprintf('\n=== validate_vs_car: harness self-test ===\n');

M  = dualtrack_build();
P  = ifssim_load_workspace();
K_TRUE = 0.75;            % road-wheel rad per steer_rad, the scale to recover

% ---- a manoeuvre that exercises the lateral dynamics -------------------
fs = 300;  t = (0:1/fs:40)';
vx = zeros(size(t));  delta = zeros(size(t));
low = t < 8;                                   % slow, held steer: calibration
vx(low)    = 3.0;
delta(low) = 0.12 * (t(low) > 2 & t(low) < 6);
ramp = t >= 8 & t < 14;                        % accelerate to 12 m/s
vx(ramp) = 3 + (t(ramp)-8)/6 * 9;
fast = t >= 14;
vx(fast) = 12;
sl = t >= 14 & t < 28;                         % slalom, ~1 g peaks
delta(sl) = 0.08 * sin(2*pi*0.5*(t(sl)-14));
ci = t >= 28;                                  % steady circle
delta(ci) = 0.10;
Y = dualtrack_sim(t, delta, vx, M);

% ---- write it out as a "recorded" run ----------------------------------
rng(7);
ax = Y.ax + 0.15*randn(size(t));
ay = Y.ay + 0.20*randn(size(t));
r  = Y.r  + 0.01*randn(size(t));
spikes = [3001 6200 9000 9001 11800];          % 16 g glitches, as recorded
ax(spikes) = -160;  ay(spikes(1:2)) = 37.9;
rpm = vx / P.WheelRadius * P.GearRatio * 60/(2*pi);
csv = fullfile(tempdir, 'ifssim_synthetic_car.csv');
writetable(table(t, delta/K_TRUE, rpm, r, ax, ay, 'VariableNames', ...
    {'t_s','steer_rad','motor_rpm','yaw_rate_rps','ax_mps2','ay_mps2'}), csv);

% ---- 1. the front end recovers the steering scale ----------------------
D = vd_car_data(csv);
ok = check(ok, 'steering scale recovered from kinematic regime', ...
           D.steer.k, K_TRUE, 0.05*K_TRUE);
ok = check(ok, 'every injected spike was gated out', ...
           round(D.rejected.ax * numel(t)), numel(spikes), 0);

% ---- 2. identity: the generating model scores near-perfect -------------
D = vd_car_data(csv, struct('steerScale', K_TRUE));
R0 = validate_vs_car(D, M, struct('vmin', 5));
fprintf('        identity: fit %.2f%%  RMSE ay %.3f  r %.4f\n', ...
        R0.fit_pct, R0.rmse.ay, R0.rmse.r);
ok = check(ok, 'identity: yaw-rate fit >= 95%', R0.fit_pct >= 95, true, 0);

% ---- 3. discrimination: wrong models score clearly worse ---------------
% Pre-committed rule: a wrong model must at least DOUBLE the yaw-rate RMSE of
% the right one. Anything less and noise alone could explain the difference.
mut = { 'yaw inertia x2',  @(m) setf(m,'Izz', m.Izz*2)
        'grip x0.8',       @(m) setf(m,'mu',  m.mu*0.8) };
for k = 1:size(mut,1)
    Mk = mut{k,2}(M);
    if isfield(Mk,'PDY1') && strcmp(mut{k,1},'grip x0.8'), Mk.PDY1 = Mk.PDY1*0.8; end
    Rk = validate_vs_car(D, Mk, struct('vmin', 5));
    fprintf('        %-15s fit %.2f%%  RMSE ay %.3f  r %.4f  (%.1fx identity)\n', ...
            mut{k,1}, Rk.fit_pct, Rk.rmse.ay, Rk.rmse.r, Rk.rmse.r / R0.rmse.r);
    ok = check(ok, ['discriminates: ' mut{k,1}], Rk.rmse.r >= 2*R0.rmse.r, true, 0);
end

fprintf('\n%s\n', tern(ok, 'harness self-test PASS.', 'HARNESS SELF-TEST FAILED.'));
end

% -------------------------------------------------------------------------
function m = setf(m, f, v), m.(f) = v; end

function ok = check(ok, name, got, want, tol)
if islogical(got) || islogical(want)
    pass = isequal(logical(got), logical(want));
    fprintf('  [%s] %s\n', tern(pass,'ok  ','FAIL'), name);
else
    pass = abs(got - want) <= tol;
    fprintf('  [%s] %-46s got %+.4g  want %+.4g\n', tern(pass,'ok  ','FAIL'), name, got, want);
end
if ~pass, ok = false; end
end

function s = tern(c,a,b), if c, s=a; else, s=b; end, end
