function ok = build_car(what)
%BUILD_CAR  One command. Edit CAR_SPEC, run this, everything downstream follows.
%
%   BUILD_CAR            check the car and write settings.json
%   BUILD_CAR('plant')   ... and rebuild the Simulink plant
%   BUILD_CAR('all')     ... and export the FMU the UE5 simulator loads
%
%   The direction of dependency USED to run the other way: settings.json was
%   edited by hand and MATLAB read it. That meant a number could be changed in
%   one place and silently disagree with the model built from it, which is how
%   the wheelbase came to be 57 mm longer than the distance between the wheel
%   centres for years.
%
%   Now CAR_SPEC is the only thing anybody edits and settings.json is an
%   OUTPUT. It is still written surgically -- value by value, leaving every
%   other line untouched -- because the file also carries sensor
%   configuration, mission settings and explanatory comments that this
%   function does not own and must not disturb.
%
%   See also CAR_SPEC, CHECK_CAR.

if nargin < 1, what = 'settings'; end
here = fileparts(mfilename('fullpath'));
root = fullfile(here,'..','..');
addpath(here); addpath(fullfile(root,'matlab','plant'));

C  = car_spec();
ok = check_car(C);
if ~ok
    fprintf('\nBUILD_CAR STOPPED: the car did not pass its own checks.\n');
    return
end

%% ---- settings.json ----------------------------------------------------
sj = fullfile(root,'settings.json');
txt = fileread(sj);
orig = txt;
changed = {};

for i = 1:numel(C.Order)
    f = C.Fields.(C.Order{i});
    key = f.name;
    if contains(key,'.')
        parts = split(key,'.');
        grp   = parts{1};
        % ONLY Pacejka is a real nested group in settings.json. Cell and Pack
        % are plant-side blocks the simulator does not carry, and flattening a
        % dotted name to its last segment silently wrote Cell.Mass into the
        % car's Mass -- settings.json went from 275 kg to 0.0467, the derived
        % wheel loads collapsed, and the tyre block failed to compile with a
        % port-dimension error three files away. Nothing in the chain said
        % 'mass'.
        if ~strcmp(grp,'Pacejka'), continue; end
        key = parts{end};
    end
    % A dotted name must never collide with a top-level one. If Pacejka ever
    % gains a field that shares a name with a vehicle parameter, fail loudly
    % rather than overwrite it.
    if contains(f.name,'.')
        clash = any(strcmp(key, cellfun(@(k) C.Fields.(k).name, C.Order, 'uni', 0)));
        if clash
            error('build_car:keyClash', ...
                  '%s flattens to "%s", which is also a top-level parameter.', f.name, key);
        end
    end
    pat = ['("' key '"\s*:\s*)(-?[0-9][0-9eE.+-]*)'];
    tok = regexp(txt, pat, 'tokens', 'once');
    if isempty(tok)
        fprintf('  [WARN] %s is not in settings.json; skipped\n', f.name);
        continue
    end
    before = str2double(tok{2});
    after  = f.value;
    if ~isequaln(before, after)
        changed{end+1} = sprintf('%s: %s -> %s', f.name, num2str(before), fmt(after)); %#ok<AGROW>
    end
    % Keep the number looking the way it already looked. If the file wrote
    % 27000.0 we write 27000.0, not 27000: JSON distinguishes the two, a
    % strict C++ parser may as well, and a generated file whose diff is full
    % of cosmetic churn is one nobody will read the real changes out of.
    txt = regexprep(txt, pat, ['$1' regexptranslate('escape', ...
                    fmt(after, contains(tok{2},'.'), numDecimals(tok{2})))], 'once');
end

% A banner, so nobody edits the output by hand and wonders why it reverts.
banner = ['"_comment_generated": "GENERATED BY matlab/car/build_car.m FROM ' ...
          'matlab/car/car_spec.m. Do not edit the physics values here by hand -- ' ...
          'they will be overwritten on the next build, and the plant and this ' ...
          'file would disagree in the meantime, which is the exact failure this ' ...
          'mechanism exists to prevent. Edit car_spec.m instead. Sensors and ' ...
          'mission settings below are NOT generated and are safe to edit here.",'];
if ~contains(txt,'"_comment_generated"')
    txt = regexprep(txt, '("VehiclePhysics"\s*:\s*\{\s*\n)', ...
                    ['$1        ' regexptranslate('escape', banner) '\n'], 'once');
    changed{end+1} = '(added the generated-file banner)';
end

if strcmp(txt, orig)
    fprintf('\nsettings.json already matches car_spec -- nothing written.\n');
else
    fid = fopen(sj,'w');  fwrite(fid, txt);  fclose(fid);
    fprintf('\nwrote %s\n', sj);
    for i = 1:numel(changed), fprintf('   %s\n', changed{i}); end
end

% Parse what we just wrote, and check it says what we meant. A surgical edit
% that produces invalid JSON, or writes into the wrong key, would otherwise
% only surface when the simulator failed to start.
try
    S = jsondecode(fileread(sj));
catch e
    error('build_car:badJson', ...
          'settings.json is no longer valid JSON after writing: %s', e.message);
end
vn = fieldnames(S.Vehicles); P = S.Vehicles.(vn{1}).VehiclePhysics;
for i = 1:numel(C.Order)
    f = C.Fields.(C.Order{i});
    if contains(f.name,'.')
        parts = split(f.name,'.');
        if ~isfield(P,parts{1}), continue; end
        got = P.(parts{1}).(parts{2});
    else
        if ~isfield(P,f.name), continue; end
        got = P.(f.name);
    end
    if abs(got - f.value) > 1e-9*max(1,abs(f.value))
        error('build_car:mismatch','%s reads back as %g, expected %g', f.name, got, f.value);
    end
end
fprintf('verified: settings.json parses and every generated value reads back correctly.\n');

% The Tyre.* group does NOT reach settings.json -- those coefficients belong
% to the Simulink tyre model, not to the simulator's own physics. car_spec
% still carries them because this file is where a number gets a source, and
% that leaves two copies of each: the sourced one here and the live one in
% ifssim_params. Two copies with nothing tying them together is how the
% numbers in this project drifted apart in the first place, so they are tied
% together here. A Tyre.X entry must match P.Assumed.TyreX exactly.
Pp = ifssim_params();
for i = 1:numel(C.Order)
    f = C.Fields.(C.Order{i});
    if ~startsWith(f.name,'Tyre.'), continue; end
    live = ['Tyre' extractAfter(f.name,'Tyre.')];
    if ~isfield(Pp.Assumed, live)
        error('build_car:noLiveTyreParam', ...
              ['car_spec declares %s but ifssim_params has no P.Assumed.%s, ' ...
               'so the sourced value reaches nothing.'], f.name, live);
    end
    if abs(Pp.Assumed.(live) - f.value) > 1e-9*max(1,abs(f.value))
        error('build_car:tyreDrift', ...
              ['%s is %g in car_spec but P.Assumed.%s is %g. The plant uses ' ...
               'the second one; the first is what anybody reads for a source.'], ...
              f.name, f.value, live, Pp.Assumed.(live));
    end
end
fprintf('verified: the Tyre.* group agrees with ifssim_params.\n');

%% ---- the plant --------------------------------------------------------
if any(strcmp(what,{'plant','all'}))
    fprintf('\nbuilding the Simulink plant...\n');
    old = cd(fullfile(root,'matlab','plant'));
    c = onCleanup(@() cd(old));
    ifssim_plant_build;
end
if strcmp(what,'all')
    fprintf('\nexporting the FMU...\n');
    export_plant_fmu;
end

fprintf('\nBUILD_CAR done.\n');
end

%% =======================================================================
function s = fmt(v, wantDot, nDec)
%FMT  Write a number the way a human would, and never in scientific notation:
%     settings.json is read by a C++ parser and by people.
if nargin < 2, wantDot = (v ~= round(v)); end
if nargin < 3, nDec = 0; end
if v == round(v) && abs(v) < 1e15
    if wantDot
        s = sprintf('%.*f', max(nDec,1), v);
    else
        s = sprintf('%d', v);
    end
else
    s = strtrim(sprintf('%.10g', v));
    if nDec > 0
        cand = strtrim(sprintf('%.*f', nDec, v));
        if abs(str2double(cand) - v) < 1e-12*max(1,abs(v)), s = cand; end
    end
end
end

function n = numDecimals(tokStr)
%NUMDECIMALS  How many digits the file already used after the point.
k = strfind(tokStr,'.');
if isempty(k), n = 0; else, n = numel(tokStr) - k(1); end
end
